name: image

on: push

jobs:
  build-container:
    name : Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: gmuchima
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gmuchima/docker-week10:final-project

      - name: Analyze with CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
         category: "/language:${{matrix.language}}"
